name: Librespeed - Package with Docker
on:
  push:
    branches:
      - main
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'actions-scan/trivy:${{ github.sha }}'
    steps:
      - name: Checkout
        id: step_one
        uses: actions/checkout@v4
        
      - name: Build an image from Dockerfile
        id: step_two
        run: |
          docker build -t ${{ env.IMAGE }} ./.
          
      - name: Run Trivy vulnerability scanner
        id: step_three
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          
      - name: Set up QEMU
        id: step_four
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Build
        id: step_five
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        id: step_six
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker images
        id: step_seven
        uses: docker/build-push-action@v5
        with:
          context: ./.
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: nghiahl/librespeed:latest
